INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (101, 'Vật Lý');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (100, 'Toán học');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (102, 'Hóa học');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (103, 'Sinh học');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (104, 'Lịch sử');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (105, 'Địa lý');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (106, 'Ngữ Văn');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (107, 'Đạo đức');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (108, 'Thể dục');