--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3
-- Dumped by pg_dump version 14.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: BangDiem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BangDiem" (
    "ID" integer NOT NULL,
    "Diem15Phut" real,
    "Diem1Tiet" real,
    "DiemCuoiKy" real,
    "HocKy" integer NOT NULL,
    "MonHocID" integer NOT NULL,
    "HocSinhID" integer NOT NULL
);


ALTER TABLE public."BangDiem" OWNER TO postgres;

--
-- Name: BangDiem_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."BangDiem" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BangDiem_ID_seq"
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: HocSinh; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."HocSinh" (
    "ID" integer NOT NULL,
    "MaSo" integer NOT NULL,
    "HoTen" character varying(255) NOT NULL,
    "NgaySinh" date,
    "DiaChi" character varying(255),
    "Email" character varying(50),
    "LopID" integer,
    "GioiTinh" integer DEFAULT 1 NOT NULL
);


ALTER TABLE public."HocSinh" OWNER TO postgres;

--
-- Name: HocSinh_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."HocSinh" ALTER COLUMN "ID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."HocSinh_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Lop; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Lop" (
    "ID" integer NOT NULL,
    "Ten" character varying(255) NOT NULL,
    "Khoi" integer NOT NULL
);


ALTER TABLE public."Lop" OWNER TO postgres;

--
-- Name: Lop_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Lop" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Lop_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MonHoc; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MonHoc" (
    "ID" integer NOT NULL,
    "MaBM" integer NOT NULL,
    "Ten" character varying(255) NOT NULL
);


ALTER TABLE public."MonHoc" OWNER TO postgres;

--
-- Name: MonHoc_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MonHoc" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MonHoc_ID_seq"
    START WITH 10
    INCREMENT BY 1
    MINVALUE 10
    NO MAXVALUE
    CACHE 1
);


--
-- Name: QuyDinh; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."QuyDinh" (
    "ID" integer NOT NULL,
    "Ten" character varying(50) NOT NULL,
    "KieuDuLieu" character varying(50) NOT NULL,
    "GiaTri" character varying(255) NOT NULL
);


ALTER TABLE public."QuyDinh" OWNER TO postgres;

-- Name: BangDiem BangDiem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BangDiem"
    ADD CONSTRAINT "BangDiem_pkey" PRIMARY KEY ("ID");


--
-- Name: HocSinh HocSinh_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HocSinh"
    ADD CONSTRAINT "HocSinh_pkey" PRIMARY KEY ("ID");


--
-- Name: Lop Lop_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lop"
    ADD CONSTRAINT "Lop_pkey" PRIMARY KEY ("ID");


--
-- Name: MonHoc MonHoc_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MonHoc"
    ADD CONSTRAINT "MonHoc_pkey" PRIMARY KEY ("ID");


--
-- Name: QuyDinh QuyDinh_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."QuyDinh"
    ADD CONSTRAINT "QuyDinh_pkey" PRIMARY KEY ("ID");


--
-- Name: BangDiem HocSinhID_IDHocSinh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BangDiem"
    ADD CONSTRAINT "HocSinhID_IDHocSinh" FOREIGN KEY ("HocSinhID") REFERENCES public."HocSinh"("ID") NOT VALID;


--
-- Name: HocSinh LopID_ID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HocSinh"
    ADD CONSTRAINT "LopID_ID" FOREIGN KEY ("LopID") REFERENCES public."Lop"("ID") NOT VALID;


--
-- Name: BangDiem MonHocID_IDMonHoc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BangDiem"
    ADD CONSTRAINT "MonHocID_IDMonHoc" FOREIGN KEY ("MonHocID") REFERENCES public."MonHoc"("ID") NOT VALID;


--
-- PostgreSQL database dump complete
--

-- insert classes of grade 10
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('10A1', 10);
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('10A2', 10);
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('10A3', 10);
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('10A4', 10);

-- insert classes of grade 11
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('11A1', 11);
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('11A2', 11);
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('11A3', 11);

-- insert classes of grade 12
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('12A1', 12);
INSERT INTO public."Lop"("Ten", "Khoi") VALUES ('12A2', 12);


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1002, 'Lê Hạnh Thìn', 0,'2003-12-15', 'Phường 6, Quận 9, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1003, 'Võ Hạnh Hải', 0,'2001-04-20', 'Phường 2, Quận 3, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1004, 'Trần Đình Ngọc', 0,'2003-11-19', 'Phường 10, Quận 8, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1005, 'Thái Thị Dương', 0,'2001-09-01', 'Phường 9, Quận 6, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1006, 'Triệu Văn Trân', 0,'2001-07-05', 'Phường 6, Quận 4, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1007, 'Tôn Xuân Loan', 1,'2003-04-03', 'Phường 8, TP. Thủ Đức, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1008, 'Thái Thị Hùng', 0,'2003-02-07', 'Phường 3, Quận 11, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1009, 'Võ Thị Phương', 1,'2002-08-06', 'Phường 6, Quận 9, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1010, 'Lê Kim Giang', 0,'2004-03-11', 'Phường 1, Quận 12, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1011, 'Võ Văn Duy', 0,'2004-02-24', 'Phường 7, Huyện Nhà Bè, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1012, 'Đinh Thanh Vy', 1,'2001-06-17', 'Phường 3, Quận 2, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1013, 'Tôn Quốc Hùng', 1,'2004-05-09', 'Phường 2, Huyện Nhà Bè, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1014, 'Võ Tấn Phương', 0,'2002-09-05', 'Phường 9, Quận 10, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1015, 'Trần Tấn Bài', 1,'2002-03-25', 'Phường 6, Quận 5, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1016, 'Lê Lan Duy', 0,'2001-08-28', 'Phường 10, Quận 2, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1017, 'Võ Nhật Châu', 0,'2003-08-14', 'Phường 5, Quận 10, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1018, 'Triệu Hạnh Dũng', 0,'2004-02-24', 'Phường 9, Quận 11, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1019, 'Tôn Quốc Hạnh', 0,'2001-03-30', 'Phường 11, Quận 4, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1020, 'Trương Thanh Hạnh', 0,'2002-03-20', 'Phường 3, Quận 11, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1021, 'Thái Quốc Ni', 0,'2003-02-26', 'Phường 1, Quận 5, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1022, 'Đinh Văn Ngân', 1,'2004-11-09', 'Phường 11, Quận 9, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1023, 'Triệu Quốc Đạt', 0,'2002-11-30', 'Phường 8, Quận 2, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1024, 'Lý Tấn Hiền', 0,'2004-05-27', 'Phường 11, Quận 10, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1025, 'Triệu Xuân Vy', 1,'2002-04-29', 'Phường 4, Huyện Hóc Môn, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1026, 'Triệu Nhật Tịnh', 1,'2001-02-19', 'Phường 2, Huyện Nhà Bè, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1027, 'Nguyễn Văn Huệ', 0,'2003-03-18', 'Phường 4, Quận 10, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1028, 'Võ Xuân Tiến', 0,'2003-12-10', 'Phường 1, Huyện Củ Chi, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1029, 'Lê Văn Như', 0,'2002-05-07', 'Phường 8, Huyện Nhà Bè, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1030, 'Trương Đình Hạnh', 1,'2004-06-09', 'Phường 7, TP. Thủ Đức, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1031, 'Tôn Nhật Hưng', 0,'2002-09-18', 'Phường 6, Huyện Củ Chi, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1032, 'Lý Hạnh Anh', 1,'2003-12-06', 'Phường 11, Huyện Hóc Môn, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1033, 'Lý Xuân Đức', 0,'2003-11-24', 'Phường 10, Quận 7, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1034, 'Thái Quốc Lộc', 0,'2003-05-03', 'Phường 9, Quân 1, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1035, 'Đinh Hồng Ni', 0,'2002-09-29', 'Phường 5, Huyện Củ Chi, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1036, 'Trương Thị Ngân', 1,'2002-06-21', 'Phường 8, Quận 6, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1037, 'Đinh Quốc Hùng', 1,'2004-03-25', 'Phường 11, TP. Thủ Đức, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1038, 'Võ Tấn Yên', 1,'2001-01-05', 'Phường 6, Quận 4, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1039, 'Triệu Quốc Giang', 0,'2001-11-02', 'Phường 4, Quận 3, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1040, 'Nguyễn Thanh Hùng', 1,'2004-04-23', 'Phường 4, Huyện Củ Chi, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1041, 'Trương Văn Như', 0,'2003-11-07', 'Phường 8, Quận 12, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1042, 'Thái Nhật Hùng', 0,'2002-08-12', 'Phường 8, Huyện Hóc Môn, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1043, 'Lý Kim Duy', 0,'2002-04-14', 'Phường 1, Quận 8, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1044, 'Triệu Đình Anh', 0,'2004-12-22', 'Phường 3, Quận 11, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1045, 'Trương Lan Loan', 0,'2003-09-16', 'Phường 2, Quân 1, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1046, 'Triệu Kim Tiến', 1,'2003-08-17', 'Phường 7, Quận 2, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1047, 'Đinh Nhật Trang', 1,'2003-11-28', 'Phường 11, Quận 5, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1048, 'Trương Văn Hải', 0,'2004-06-06', 'Phường 11, Huyện Củ Chi, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1049, 'Lý Kim Long', 1,'2004-10-17', 'Phường 1, Quận 12, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1050, 'Lý Hồng Lộc', 0,'2002-11-02', 'Phường 7, TP. Thủ Đức, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1051, 'Đinh Hạnh Long', 0,'2003-02-13', 'Phường 2, Quận 8, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1052, 'Võ Xuân Dương', 0,'2004-12-10', 'Phường 10, Quận 9, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1053, 'Trương Hồng Đức', 0,'2001-11-30', 'Phường 2, Quận 4, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1054, 'Lê Đình Thắm', 0,'2002-03-25', 'Phường 10, Huyện Hóc Môn, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1055, 'Trương Lan Yên', 1,'2003-09-14', 'Phường 8, Quận 12, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1056, 'Trần Quốc Nguyên', 1,'2002-03-13', 'Phường 10, Huyện Củ Chi, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1057, 'Tôn Hồng Nguyên', 0,'2001-04-20', 'Phường 4, Quận 10, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1058, 'Đinh Thanh Anh', 0,'2003-07-21', 'Phường 8, Quận 11, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1059, 'Thái Xuân Đức', 0,'2004-10-23', 'Phường 10, TP. Thủ Đức, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1060, 'Nguyễn Hạnh Vy', 0,'2003-10-23', 'Phường 10, Quận 10, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1061, 'Đinh Kim Duy', 0,'2004-01-14', 'Phường 5, Quận 2, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1062, 'Võ Hồng Châu', 0,'2002-08-16', 'Phường 1, Quân 1, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1063, 'Lý Thị Long', 1,'2003-05-05', 'Phường 11, Quận 8, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1064, 'Trần Lan Ngọc', 1,'2001-12-08', 'Phường 3, Quận 5, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1065, 'Đinh Tấn Tiến', 1,'2002-06-08', 'Phường 8, Quận 12, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1066, 'Lê Hạnh Nhàn', 0,'2002-06-04', 'Phường 4, TP. Thủ Đức, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1067, 'Đinh Hồng Dương', 0,'2003-11-29', 'Phường 7, Quận 4, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1068, 'Võ Nhật Hải', 1,'2001-04-02', 'Phường 5, Quận 7, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1069, 'Nguyễn Thị Thìn', 0,'2002-06-16', 'Phường 9, Quận 6, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1070, 'Võ Hồng Giáp', 0,'2001-02-11', 'Phường 3, Quận 4, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1071, 'Tôn Xuân Trân', 0,'2004-12-04', 'Phường 10, Quận 4, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1072, 'Thái Thanh Ngọc', 0,'2003-09-20', 'Phường 2, Quận 3, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1074, 'Tôn Xuân Hạnh', 1,'2002-02-18', 'Phường 9, Quận 9, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1075, 'Tôn Văn Yên', 0,'2001-07-27', 'Phường 6, Quận 10, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1076, 'Nguyễn Đình Giáp', 0,'2002-04-03', 'Phường 8, Quân 1, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1077, 'Triệu Văn Như', 1,'2003-08-14', 'Phường 11, Huyện Củ Chi, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1078, 'Trương Xuân Hạnh', 1,'2004-12-15', 'Phường 4, Huyện Hóc Môn, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1079, 'Lê Kim Nghi', 0,'2001-06-27', 'Phường 1, Quận 10, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1080, 'Võ Văn Giang', 0,'2002-01-18', 'Phường 7, Quận 6, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1081, 'Lý Đình Ngọc', 1,'2003-11-26', 'Phường 5, Quận 9, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1082, 'Triệu Kim Loan', 0,'2004-06-01', 'Phường 9, Quận 10, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1083, 'Đinh Đình Yên', 0,'2001-03-22', 'Phường 1, Quận 2, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1084, 'Nguyễn Quốc Nam', 0,'2003-06-17', 'Phường 9, Quận 7, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1085, 'Trương Đình Bài', 1,'2003-05-04', 'Phường 1, Quân 1, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1086, 'Triệu Lan Nam', 1,'2004-09-15', 'Phường 8, Huyện Hóc Môn, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1087, 'Trương Đình Thắm', 0,'2002-09-04', 'Phường 6, Quận 11, TP. HCM', 'iloveyou@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1089, 'Triệu Thị Hùng', 0,'2001-11-20', 'Phường 9, TP. Thủ Đức, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1090, 'Đinh Kim Nam', 0,'2003-12-27', 'Phường 5, Quận 12, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1091, 'Tôn Nhật Hùng', 0,'2004-06-06', 'Phường 7, Quận 12, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1092, 'Lý Hạnh Đức', 1,'2001-01-07', 'Phường 10, TP. Thủ Đức, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1093, 'Đinh Thị Phúc', 0,'2003-03-08', 'Phường 10, Quận 6, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1094, 'Thái Thị Duy', 0,'2001-02-27', 'Phường 8, Quận 8, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1096, 'Nguyễn Văn Duy', 1,'2001-08-06', 'Phường 5, Quận 5, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1095, 'Thái Nhật Quỳnh', 0,'2004-01-23', 'Phường 6, Quận 10, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1097, 'Võ Hồng Hạnh', 1,'2001-02-04', 'Phường 8, Huyện Củ Chi, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1098, 'Võ Hồng Nguyên', 1,'2004-07-26', 'Phường 8, Quận 12, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1099, 'Triệu Kim Long', 1,'2003-08-03', 'Phường 3, TP. Thủ Đức, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1100, 'Trần Hạnh Bài', 0,'2004-09-09', 'Phường 3, Quận 11, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1101, 'Lý Kim Dương', 0,'2003-04-17', 'Phường 11, Quận 12, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1102, 'Lê Quốc Phúc', 0,'2004-05-06', 'Phường 3, Quân 1, TP. HCM', 'ha@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1104, 'Nguyễn Quốc Như', 1,'2003-10-05', 'Phường 7, Quận 11, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1105, 'Lê Lan Đức', 0,'2003-03-09', 'Phường 9, Quân 1, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1106, 'Trương Hạnh Hạnh', 1,'2001-04-26', 'Phường 5, Huyện Nhà Bè, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1107, 'Trần Xuân Hiền', 0,'2002-10-01', 'Phường 5, Huyện Hóc Môn, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1108, 'Lý Đình Trân', 0,'2001-02-10', 'Phường 4, Quận 10, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1109, 'Nguyễn Quốc Nga', 0,'2002-02-26', 'Phường 4, Quận 3, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1110, 'Nguyễn Hạnh Như', 1,'2004-07-16', 'Phường 10, Quận 3, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1111, 'Trương Quốc Châu', 0,'2001-08-10', 'Phường 9, Quận 10, TP. HCM', 'datohyeah@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1113, 'Đinh Thị Nghi', 0,'2004-10-07', 'Phường 7, Quận 3, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1114, 'Lê Hạnh Tiến', 0,'2003-11-12', 'Phường 7, Quận 9, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1115, 'Trần Thị Lộc', 1,'2001-01-28', 'Phường 3, Quận 4, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1116, 'Triệu Xuân Châu', 0,'2001-06-26', 'Phường 7, Quận 4, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1117, 'Đinh Văn Lộc', 0,'2002-12-17', 'Phường 2, Quận 9, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1118, 'Võ Quốc Loan', 1,'2001-03-16', 'Phường 4, Quận 11, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1119, 'Trần Quốc Đức', 0,'2001-08-31', 'Phường 6, Quận 8, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1120, 'Lý Quốc Ngân', 0,'2003-05-15', 'Phường 4, Huyện Nhà Bè, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1121, 'Võ Tấn Ngọc', 0,'2002-04-03', 'Phường 5, Quận 8, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1122, 'Trần Kim Thìn', 1,'2002-05-09', 'Phường 10, Quận 10, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1123, 'Trần Hạnh Thắm', 0,'2003-05-18', 'Phường 10, Quận 9, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1124, 'Nguyễn Hạnh Phương', 1,'2001-03-29', 'Phường 2, Huyện Nhà Bè, TP. HCM', 'daklak@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1126, 'Lê Lan Trãi', 1,'2003-01-26', 'Phường 6, Huyện Nhà Bè, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1127, 'Nguyễn Thanh Ngân', 0,'2002-02-05', 'Phường 9, Quận 2, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1128, 'Triệu Thanh Tiến', 1,'2004-05-02', 'Phường 2, Quận 11, TP. HCM', 'duc@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1130, 'Lý Tấn Nguyên', 1,'2004-02-20', 'Phường 9, Huyện Nhà Bè, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1131, 'Tôn Kim Duy', 0,'2004-04-17', 'Phường 4, Quận 8, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1132, 'Thái Nhật Vy', 1,'2001-05-31', 'Phường 5, Huyện Hóc Môn, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1133, 'Đinh Hồng Hùng', 0,'2001-02-04', 'Phường 3, Quận 2, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1134, 'Đinh Kim Phúc', 0,'2002-05-23', 'Phường 10, Quận 3, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1135, 'Nguyễn Nhật Nhàn', 1,'2003-12-18', 'Phường 8, Huyện Nhà Bè, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1136, 'Tôn Quốc Loan', 0,'2001-08-28', 'Phường 8, Quận 3, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1137, 'Tôn Nhật Quỳnh', 0,'2003-10-25', 'Phường 7, Quận 4, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1138, 'Tôn Văn Đức', 1,'2003-07-30', 'Phường 6, Quận 11, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1139, 'Trần Hồng Tiến', 0,'2002-05-28', 'Phường 3, Quận 2, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1140, 'Nguyễn Tấn Phương', 0,'2002-05-26', 'Phường 9, Quận 7, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1141, 'Lý Kim Hải', 0,'2003-09-27', 'Phường 7, Huyện Hóc Môn, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1142, 'Trương Lan Hưng', 0,'2003-09-16', 'Phường 10, Huyện Nhà Bè, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1143, 'Lý Kim Nghi', 0,'2004-10-15', 'Phường 8, Quận 10, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1144, 'Võ Thị Phương', 0,'2001-06-03', 'Phường 1, TP. Thủ Đức, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1145, 'Trần Lan Vy', 0,'2003-02-13', 'Phường 9, Huyện Củ Chi, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1146, 'Đinh Thanh Nhàn', 1,'2001-10-03', 'Phường 5, Huyện Hóc Môn, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1147, 'Lê Xuân Nga', 0,'2003-11-30', 'Phường 5, Quận 4, TP. HCM', 'thandong@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1149, 'Đinh Đình Giang', 0,'2003-06-15', 'Phường 4, Quân 1, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1150, 'Lê Xuân Trãi', 0,'2001-07-02', 'Phường 11, Quận 10, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1151, 'Tôn Hạnh Long', 0,'2004-11-22', 'Phường 11, Huyện Củ Chi, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1152, 'Thái Văn Trân', 0,'2002-03-30', 'Phường 8, Huyện Củ Chi, TP. HCM', 'nga@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1154, 'Nguyễn Hồng Trãi', 0,'2001-11-08', 'Phường 4, Huyện Nhà Bè, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1155, 'Lê Thị Hạnh', 0,'2003-03-16', 'Phường 10, Quận 4, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1156, 'Thái Thanh Nhàn', 0,'2001-10-01', 'Phường 10, Quận 7, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1157, 'Triệu Kim Hải', 1,'2003-09-13', 'Phường 2, Quận 10, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1158, 'Lê Thị Trân', 0,'2001-08-19', 'Phường 6, Quận 10, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1159, 'Thái Lan Hiền', 0,'2004-06-16', 'Phường 10, Huyện Nhà Bè, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1160, 'Võ Hồng Hạnh', 1,'2004-10-29', 'Phường 1, Quận 11, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1161, 'Tôn Thị Tý', 1,'2001-03-13', 'Phường 1, Quận 10, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1162, 'Triệu Quốc Bài', 0,'2002-09-02', 'Phường 3, Quân 1, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1163, 'Lý Tấn Hưng', 0,'2001-07-22', 'Phường 8, Quận 10, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1164, 'Trương Hạnh Loan', 0,'2004-06-26', 'Phường 2, Quân 1, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1165, 'Triệu Kim Bài', 1,'2004-09-06', 'Phường 6, Quận 12, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1166, 'Nguyễn Hồng Châu', 0,'2004-12-23', 'Phường 7, Quận 11, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1167, 'Triệu Thanh Ni', 1,'2004-09-26', 'Phường 5, Quận 6, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1168, 'Trương Thanh Dũng', 0,'2001-06-18', 'Phường 4, Quận 7, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1169, 'Đinh Xuân Giang', 0,'2003-12-29', 'Phường 2, Quận 12, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1170, 'Lý Thị Loan', 1,'2004-12-10', 'Phường 1, Quận 8, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1171, 'Võ Thanh Giang', 1,'2004-05-31', 'Phường 4, Quận 3, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1172, 'Triệu Đình Huệ', 1,'2003-08-13', 'Phường 1, Quận 12, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1173, 'Võ Tấn Dũng', 0,'2001-05-04', 'Phường 9, Quận 4, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1174, 'Thái Nhật Thìn', 1,'2001-07-19', 'Phường 4, Quận 2, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1175, 'Trần Tấn Giáp', 0,'2004-04-11', 'Phường 9, TP. Thủ Đức, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1177, 'Triệu Kim Loan', 0,'2004-02-02', 'Phường 4, Quận 9, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1176, 'Đinh Đình Yên', 0,'2002-10-01', 'Phường 11, Quận 12, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1178, 'Đinh Nhật Nhàn', 0,'2001-12-15', 'Phường 7, TP. Thủ Đức, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1179, 'Đinh Nhật Long', 0,'2004-01-26', 'Phường 6, Quận 7, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1180, 'Trần Quốc Lộc', 1,'2002-06-01', 'Phường 5, Quận 3, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1181, 'Triệu Quốc Giáp', 1,'2003-03-27', 'Phường 2, Quận 11, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1182, 'Võ Thị Quỳnh', 0,'2001-07-31', 'Phường 3, Quận 5, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1183, 'Nguyễn Quốc Hiền', 0,'2004-04-19', 'Phường 2, Quận 12, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1184, 'Lê Xuân Hạnh', 1,'2001-02-21', 'Phường 2, Quận 3, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1185, 'Lê Thị Đức', 1,'2001-11-19', 'Phường 5, Quận 7, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1186, 'Thái Hạnh Phúc', 1,'2004-03-22', 'Phường 4, Quận 5, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1187, 'Đinh Hạnh Nghi', 1,'2001-04-29', 'Phường 9, TP. Thủ Đức, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1188, 'Đinh Kim Ngân', 1,'2001-06-13', 'Phường 9, Quận 2, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1189, 'Võ Quốc Hạnh', 0,'2002-06-24', 'Phường 3, Quận 7, TP. HCM', 'la@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1191, 'Đinh Hạnh Giáp', 0,'2004-11-23', 'Phường 10, Huyện Củ Chi, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1192, 'Võ Kim Duy', 0,'2002-10-17', 'Phường 5, Quận 11, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1193, 'Thái Kim Hưng', 1,'2003-12-17', 'Phường 10, Quận 9, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1194, 'Triệu Thị Nga', 0,'2003-07-10', 'Phường 6, Quân 1, TP. HCM', 'ahi@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1196, 'Lê Văn Vy', 0,'2001-01-23', 'Phường 6, Quận 8, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1197, 'Lê Đình Nam', 0,'2001-09-24', 'Phường 5, Quận 12, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1198, 'Trương Thị Thắm', 0,'2001-12-23', 'Phường 10, Huyện Hóc Môn, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1199, 'Trần Nhật Ngân', 0,'2002-07-09', 'Phường 3, Quận 6, TP. HCM', 'dalat@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1201, 'Đinh Thị Thắm', 0,'2003-12-08', 'Phường 3, Quận 11, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1202, 'Võ Tấn Hưng', 0,'2002-06-22', 'Phường 7, Quận 5, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1203, 'Lê Thanh Trãi', 0,'2004-07-04', 'Phường 11, Quận 7, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1204, 'Thái Văn Giang', 0,'2004-11-25', 'Phường 5, Huyện Nhà Bè, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1205, 'Tôn Thị Yên', 1,'2004-12-17', 'Phường 9, Quận 9, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1206, 'Lý Tấn Bài', 0,'2003-01-28', 'Phường 2, Quận 6, TP. HCM', 'ahi@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1208, 'Đinh Quốc Trãi', 0,'2004-09-22', 'Phường 7, Quận 10, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1209, 'Võ Kim Giáp', 0,'2002-07-30', 'Phường 3, Quận 12, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1210, 'Nguyễn Hạnh Châu', 1,'2004-04-11', 'Phường 2, Quận 12, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1211, 'Nguyễn Văn Tý', 0,'2002-09-25', 'Phường 7, Quận 4, TP. HCM', 'nga@gmail.com');



INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1214, 'Võ Kim Bài', 0,'2004-01-05', 'Phường 5, Quân 1, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1215, 'Trương Hồng Phương', 0,'2002-07-28', 'Phường 6, Quận 12, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1216, 'Lý Quốc Ngân', 0,'2001-01-04', 'Phường 11, Quận 8, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1217, 'Trương Tấn Giang', 1,'2001-07-07', 'Phường 11, Huyện Củ Chi, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1218, 'Đinh Văn Duy', 1,'2003-02-14', 'Phường 3, Quận 5, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1219, 'Triệu Lan Dương', 1,'2002-05-12', 'Phường 1, Quận 8, TP. HCM', 'ninja2333@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1221, 'Nguyễn Đình Nam', 0,'2004-01-21', 'Phường 10, Quân 1, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1222, 'Thái Quốc Dũng', 0,'2003-10-01', 'Phường 6, Quân 1, TP. HCM', 'hcm@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1224, 'Tôn Hạnh Giáp', 0,'2002-12-26', 'Phường 7, Quận 7, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1225, 'Nguyễn Quốc Trãi', 1,'2002-06-10', 'Phường 6, Quận 8, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1226, 'Trương Hồng Hạnh', 0,'2003-07-21', 'Phường 2, Quận 12, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1227, 'Lê Thị Ngân', 0,'2001-07-08', 'Phường 5, Quận 7, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1228, 'Trần Hồng Phúc', 1,'2002-11-28', 'Phường 8, Quận 7, TP. HCM', 'thandong@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1230, 'Thái Thị Trân', 0,'2004-05-28', 'Phường 1, Huyện Hóc Môn, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1231, 'Thái Tấn Như', 0,'2003-08-20', 'Phường 4, Quận 9, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1232, 'Trần Văn Thắm', 0,'2003-08-10', 'Phường 11, Quận 8, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1233, 'Nguyễn Thanh Anh', 1,'2003-05-04', 'Phường 1, Quận 7, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1234, 'Trương Nhật Lộc', 0,'2004-04-23', 'Phường 4, Quận 8, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1236, 'Triệu Xuân Nghi', 0,'2001-10-15', 'Phường 1, Quận 5, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1235, 'Trần Tấn Bài', 0,'2002-07-26', 'Phường 3, TP. Thủ Đức, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1237, 'Lê Hạnh Đức', 1,'2002-01-20', 'Phường 3, Quận 8, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1238, 'Tôn Xuân Lộc', 0,'2001-05-26', 'Phường 11, Quận 5, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1239, 'Trương Hồng Bài', 0,'2004-12-25', 'Phường 3, Quân 1, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1240, 'Lý Nhật Như', 0,'2003-04-17', 'Phường 7, Quận 6, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1241, 'Triệu Hạnh Ngọc', 0,'2004-10-18', 'Phường 3, Quận 2, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1242, 'Tôn Hồng Lộc', 0,'2004-04-04', 'Phường 10, Quận 10, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1243, 'Lý Hạnh Trãi', 0,'2002-06-16', 'Phường 10, Quận 9, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1244, 'Đinh Thị Tịnh', 0,'2002-07-11', 'Phường 11, Huyện Hóc Môn, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1245, 'Triệu Xuân Quỳnh', 0,'2003-12-13', 'Phường 1, Quận 9, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1246, 'Lê Đình Nghi', 1,'2003-07-02', 'Phường 7, Quận 5, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1248, 'Lê Xuân Vy', 0,'2004-07-24', 'Phường 1, Quận 8, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1247, 'Võ Thanh Trân', 0,'2004-01-12', 'Phường 1, Quận 2, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1249, 'Triệu Văn Châu', 0,'2003-09-20', 'Phường 8, Quận 10, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1250, 'Trần Nhật Huệ', 0,'2002-06-21', 'Phường 8, Quận 7, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1251, 'Lý Kim Phương', 0,'2001-07-22', 'Phường 3, Quân 1, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1252, 'Trương Thanh Anh', 0,'2004-01-16', 'Phường 8, Quận 2, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1253, 'Lý Nhật Nga', 0,'2002-07-21', 'Phường 2, Quận 12, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1254, 'Đinh Tấn Huệ', 1,'2003-01-27', 'Phường 7, Quận 12, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1255, 'Tôn Hồng Như', 0,'2003-06-20', 'Phường 6, Huyện Hóc Môn, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1256, 'Trương Tấn Vy', 1,'2002-06-13', 'Phường 11, Quận 3, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1257, 'Trần Kim Nga', 0,'2004-08-06', 'Phường 10, Quận 10, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1258, 'Thái Văn Vy', 1,'2003-01-02', 'Phường 9, Quận 3, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1259, 'Trần Quốc Anh', 0,'2004-01-01', 'Phường 8, Quận 8, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1260, 'Lý Quốc Tiến', 0,'2003-12-19', 'Phường 6, Huyện Củ Chi, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1261, 'Lý Quốc Ni', 0,'2004-04-17', 'Phường 9, Quận 5, TP. HCM', 'viet@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1263, 'Tôn Quốc Loan', 0,'2002-12-01', 'Phường 9, Quận 12, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1264, 'Nguyễn Hạnh Ngọc', 0,'2004-03-19', 'Phường 2, Quận 10, TP. HCM', 'ahi@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1266, 'Võ Thị Giáp', 0,'2003-03-06', 'Phường 11, Quận 4, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1267, 'Thái Tấn Thìn', 0,'2003-12-17', 'Phường 6, Quận 9, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1268, 'Võ Xuân Bài', 0,'2003-08-14', 'Phường 1, Quận 5, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1269, 'Triệu Lan Giáp', 0,'2001-07-26', 'Phường 11, Huyện Nhà Bè, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1270, 'Lê Xuân Châu', 0,'2004-05-04', 'Phường 7, Quận 2, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1271, 'Lý Lan Dũng', 0,'2002-08-21', 'Phường 5, Quận 7, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1272, 'Nguyễn Quốc Ni', 1,'2003-08-13', 'Phường 6, Huyện Củ Chi, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1273, 'Trương Tấn Nhàn', 1,'2002-07-01', 'Phường 6, Quận 7, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1274, 'Võ Thanh Nghi', 1,'2003-01-21', 'Phường 8, Quận 3, TP. HCM', 'daklak@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1275, 'Triệu Xuân Nghi', 0,'2001-04-01', 'Phường 7, Quận 10, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1276, 'Võ Quốc Trân', 0,'2004-11-30', 'Phường 7, Quận 5, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1277, 'Đinh Thanh Thìn', 1,'2004-08-09', 'Phường 11, Quận 10, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1278, 'Nguyễn Đình Anh', 0,'2003-08-05', 'Phường 9, Quận 2, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1279, 'Tôn Đình Anh', 0,'2001-01-22', 'Phường 11, TP. Thủ Đức, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1280, 'Thái Hạnh Nga', 0,'2001-11-16', 'Phường 11, Huyện Hóc Môn, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1281, 'Đinh Hồng Thắm', 0,'2004-04-12', 'Phường 6, Quận 11, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1282, 'Võ Nhật Nam', 0,'2004-03-25', 'Phường 10, Huyện Củ Chi, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1283, 'Lê Tấn Giáp', 0,'2002-12-24', 'Phường 5, Quận 6, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1284, 'Lý Lan Đức', 0,'2001-05-08', 'Phường 3, Quận 12, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1285, 'Lý Lan Quỳnh', 0,'2001-01-21', 'Phường 8, Quận 6, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1286, 'Trương Văn Nam', 0,'2002-09-25', 'Phường 3, Quận 6, TP. HCM', 'thandong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1287, 'Đinh Tấn Tý', 0,'2001-03-26', 'Phường 7, Quận 3, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1288, 'Lê Đình Trân', 0,'2004-12-14', 'Phường 11, Quận 12, TP. HCM', 'bi123@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1290, 'Trần Đình Hiền', 0,'2002-08-24', 'Phường 3, TP. Thủ Đức, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1291, 'Lý Nhật Hưng', 0,'2001-03-13', 'Phường 6, Quận 11, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1292, 'Trương Quốc Lộc', 0,'2001-12-24', 'Phường 7, Huyện Hóc Môn, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1293, 'Nguyễn Nhật Giáp', 1,'2001-01-22', 'Phường 11, Quận 2, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1294, 'Tôn Quốc Châu', 0,'2001-11-20', 'Phường 5, Quận 2, TP. HCM', 'bi123@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1296, 'Triệu Thị Nghi', 1,'2001-10-12', 'Phường 8, Huyện Hóc Môn, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1297, 'Triệu Hạnh Dũng', 0,'2004-01-27', 'Phường 3, Quận 3, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1298, 'Lê Kim Thìn', 0,'2001-06-11', 'Phường 4, Quận 4, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1299, 'Nguyễn Tấn Anh', 1,'2002-12-25', 'Phường 4, TP. Thủ Đức, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1300, 'Trần Xuân Quỳnh', 0,'2004-07-29', 'Phường 1, Quận 8, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1301, 'Tôn Văn Vy', 0,'2002-11-23', 'Phường 9, Quận 9, TP. HCM', 'nga@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1303, 'Lê Hạnh Tịnh', 1,'2002-08-01', 'Phường 7, Huyện Nhà Bè, TP. HCM', 'conna@gmail.com');



INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1305, 'Tôn Xuân Yên', 1,'2001-05-18', 'Phường 2, Quận 12, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1307, 'Trần Hồng Trân', 0,'2002-11-02', 'Phường 2, Quận 2, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1306, 'Lê Hồng Dũng', 0,'2001-10-14', 'Phường 4, Quận 3, TP. HCM', 'teo11@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1308, 'Tôn Hồng Đức', 0,'2004-06-03', 'Phường 10, Huyện Củ Chi, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1309, 'Trần Hồng Nga', 0,'2004-11-03', 'Phường 11, Quận 7, TP. HCM', 'la@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1310, 'Tôn Nhật Quỳnh', 0,'2001-03-16', 'Phường 6, Quận 2, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1312, 'Thái Văn Nhàn', 0,'2002-05-21', 'Phường 3, Quận 3, TP. HCM', 'ducc112@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1311, 'Thái Xuân Đức', 1,'2001-11-18', 'Phường 4, Quận 7, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1313, 'Tôn Quốc Phúc', 0,'2003-06-30', 'Phường 9, Quận 12, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1314, 'Lê Kim Lộc', 1,'2003-06-27', 'Phường 7, Quận 2, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1315, 'Trần Kim Long', 1,'2001-04-25', 'Phường 1, TP. Thủ Đức, TP. HCM', 'lamdong@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1316, 'Nguyễn Đình Hùng', 0,'2004-10-09', 'Phường 4, Quận 4, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1317, 'Đinh Văn Tý', 1,'2001-08-28', 'Phường 9, Quân 1, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1318, 'Nguyễn Quốc Dũng', 0,'2003-03-06', 'Phường 6, Quận 11, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1319, 'Tôn Đình Đức', 1,'2002-05-14', 'Phường 3, Huyện Củ Chi, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1321, 'Lê Nhật Ngọc', 1,'2003-12-11', 'Phường 1, Quận 10, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1320, 'Trương Thị Huệ', 1,'2001-05-08', 'Phường 10, Huyện Hóc Môn, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1322, 'Lý Lan Hùng', 1,'2001-07-16', 'Phường 5, Quận 4, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1323, 'Lý Hồng Hiền', 0,'2001-12-25', 'Phường 5, Quân 1, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1324, 'Triệu Hồng Long', 1,'2003-06-16', 'Phường 11, TP. Thủ Đức, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1325, 'Thái Văn Tiến', 0,'2001-06-14', 'Phường 2, Quận 11, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1326, 'Lê Hạnh Tịnh', 0,'2004-09-02', 'Phường 3, Quận 3, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1327, 'Triệu Thanh Dũng', 0,'2003-01-20', 'Phường 5, Huyện Củ Chi, TP. HCM', 'datohyeah@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1328, 'Võ Kim Như', 0,'2001-07-09', 'Phường 2, TP. Thủ Đức, TP. HCM', 'loc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1329, 'Đinh Quốc Quỳnh', 1,'2003-05-21', 'Phường 2, Quận 10, TP. HCM', 'conna@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1331, 'Đinh Kim Nhàn', 0,'2001-02-12', 'Phường 2, Quận 5, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1330, 'Võ Hồng Châu', 0,'2002-09-30', 'Phường 9, Quân 1, TP. HCM', 'ninja2333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1332, 'Nguyễn Xuân Nguyên', 1,'2003-01-11', 'Phường 8, Quận 11, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1333, 'Đinh Hồng Giáp', 0,'2002-04-08', 'Phường 9, Quận 12, TP. HCM', 'nga@gmail.com');


INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1335, 'Trương Thị Giáp', 0,'2002-09-28', 'Phường 10, Quận 4, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1336, 'Lý Quốc Hạnh', 0,'2003-08-23', 'Phường 9, Quận 10, TP. HCM', 'ti3333@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1337, 'Lê Đình Như', 0,'2002-03-10', 'Phường 7, Quân 1, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1338, 'Lý Thị Hạnh', 1,'2004-01-25', 'Phường 8, Quân 1, TP. HCM', 'ahi@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1339, 'Đinh Thị Tý', 0,'2002-12-16', 'Phường 7, Quân 1, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1340, 'Lý Quốc Đạt', 0,'2002-01-08', 'Phường 4, Huyện Nhà Bè, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1341, 'Lý Hạnh Nghi', 1,'2003-03-04', 'Phường 10, Huyện Hóc Môn, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1342, 'Trần Nhật Dương', 1,'2002-12-21', 'Phường 2, Quận 12, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1343, 'Nguyễn Hạnh Như', 1,'2003-06-08', 'Phường 7, Quân 1, TP. HCM', 'dalat@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1344, 'Triệu Kim Hưng', 0,'2001-07-26', 'Phường 8, Quận 4, TP. HCM', 'hcm@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1346, 'Võ Tấn Tiến', 0,'2002-12-16', 'Phường 6, Quận 5, TP. HCM', 'duc@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1345, 'Đinh Đình Hạnh', 0,'2002-09-08', 'Phường 9, TP. Thủ Đức, TP. HCM', 'viet@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1348, 'Lý Đình Châu', 0,'2004-04-09', 'Phường 10, Huyện Nhà Bè, TP. HCM', 'iloveyou@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1347, 'Thái Thanh Thắm', 0,'2002-04-13', 'Phường 8, Quân 1, TP. HCM', 'ha@gmail.com');

INSERT INTO public."HocSinh"("MaSo", "HoTen", "GioiTinh", "NgaySinh", "DiaChi", "Email") VALUES (1349, 'Lê Thị Tý', 0,'2002-11-21', 'Phường 11, Quận 2, TP. HCM', 'bi123@gmail.com');

INSERT INTO public."QuyDinh" ("ID", "Ten", "KieuDuLieu", "GiaTri") VALUES (1000, 'Sĩ số tối đa', 'int', '40');
INSERT INTO public."QuyDinh" ("ID", "Ten", "KieuDuLieu", "GiaTri") VALUES (1001, 'Độ tuổi tối thiểu', 'int', '15');
INSERT INTO public."QuyDinh" ("ID", "Ten", "KieuDuLieu", "GiaTri") VALUES (1002, 'Độ tuổi tối đa', 'int', '20');
INSERT INTO public."QuyDinh" ("ID", "Ten", "KieuDuLieu", "GiaTri") VALUES (1003, 'Điểm chuẩn đạt môn', 'float', '5');

INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (101, 'Vật Lý');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (100, 'Toán học');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (102, 'Hóa học');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (103, 'Sinh học');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (104, 'Lịch sử');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (105, 'Địa lý');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (106, 'Ngữ Văn');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (107, 'Đạo đức');
INSERT INTO public."MonHoc" ("MaBM", "Ten") VALUES (108, 'Thể dục');